### ISSUE TITLE
README.md Pull Request Link 에러

### ISSUE THREAD

**Issue by bigstark** [JSpiner/RESUME#10]
https://github.com/JSpiner/RESUME/blob/e699ea1401a997a2cbe744b2ded611bc5f34bf53/README.md#L196

<img width="1055" alt="2018-08-24 6 57 29" src="https://user-images.githubusercontent.com/3222096/44578844-97b39e00-a7cf-11e8-9257-761433273e45.png">

이부분에서 링크가 `...pulls)로` 까지 잡히네요. 띄어쓰기 추천드립니다.

**Comment by JSpiner** [comment]
2058af76856619940e1effe71133f269839939b9
에서 수정되었습니다.

감사합니다.
